#! /bin/bash

declare -A connectionarray
friendlynames=""

shopt -s nullglob
rawarray=(/home/uuu/.local/share/remmina/*)
shopt -u nullglob #turn off nullglob to avoid issues elsewhere

for i in "${rawarray[@]}"
do
  friendlyname=${i##*/} 							# remove leading directories
  friendlynaem=${friendlyname%.*}					# remove extension
  friendlyname=${friendlyname//group_rdp_/}			# remove prefix (add more as needed)
  friendlyname=${friendlyname%%_*}					# remove ip at the end (format _nnn-nnn-nnn-nnn)
  friendlynames="${friendlyname}\n${friendlynames}"
  connectionarray[${friendlyname}]=${i}
done

selectedconnection=$(printf $friendlynames | tofi --prompt "connect: ")

if [ -n "$selectedconnection" ]; then
	remmina ${connectionarray["${selectedconnection}"]} 
fi
