
$font-family = ProggyClean Nerd Font
$unifont = Unifont-JP
$font-size = 12
$monitor = eDP-1
$dark-color = rgb(29, 31, 33)
$light-color = rgb(193, 200, 198)
$red-color = rgb(204, 102, 102)

# GENERAL
general {
    hide_cursor = true
    immediate_render = true
}

animations {
    enabled = false
}

# BACKGROUND
background {
    monitor =
    ## disable the below to get a block color background
    path = /home/uuu/.config/hypr/stalenhag_svema.jpg
    color = $dark-color
    blur_passes = 3
}

# Day-Month-Date
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%Y年%m月%d日 %H:%M:%S")"
    color = $light-color
    font_family = $unifont
    font_size = $font-size
    position = 0, 500
    halign = center
    valign = center
    zindex = 5
}

# LOGIN-OUTLINE
shape {
    monitor =
    size = 500, 60
    color = $dark-color
    rounding = 0
    border_size = 1
    border_color = $light-color
    rotate = 0
    position = 0, 0
    halign = center
    valign = center
    zindex = 1
}

# DATE-BACKDROP-BOX
shape {
    monitor =
    size = 190, 20
    color = $dark-color
    position = 0, 500
    halign = center
    valign = center
    zindex = 0
}

# LOGIN-BACKDROP-BOX
shape {
    monitor =
    size = 518, 78
    color = $dark-color
    round = 0
    border_size = -1
    rotate = 0
    position = 0, 0
    halign = center
    valign = center
    zindex = 0
}

# AUTHENTICATE-MESSAGE-BACKDROP-BOX
shape {
    monitor =
    size = 180, 12
    color = $dark-color
    rounding = 0
    border_size = 2
    border_color = $dark-color
    rotate = 0
    position = -138, 30
    halign = center
    valign = center
    zindex = 2
}

# USER
label {
    monitor =
    text =  authenticate into fedora
    color = $light-color
    font_family = $font-family
    font_size = $font-size
    position = -138, 30
    halign = center
    valign = center
    zindex = 5
}

# USER
label {
    monitor =
    text = username: $USER
    color = $light-color
    font_family = $font-family
    font_size = $font-size
    position = -176 , 6
    halign = center
    valign = center
    zindex = 1
}

# USER
label {
    monitor =
    text = password: 
    color = $light-color
    font_family = $font-family
    font_size = $font-size
    position = -190, -6
    halign = center
    valign = center
    zindex = 5
}

# INPUT FIELD
input-field {
    monitor =
    size = 400, 50
    outline_thickness = -1
    dots_text_format = *
    #dots_size = 0.5 # Scale of input-field height, 0.2 - 0.8
    #dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = false
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(0, 0, 0, 0)
    font_family = $font-family
    font_color = $light-color
    fail_color = $red-color
    fade_on_empty = false
    placeholder_text =
    hide_input = false
    position = 30 , -6
    halign = center
    valign = center
    zindex = 5
}
