# battery settings
listener {
    timeout = 300   
    on-timeout = systemd-ac-power || hyprlock
}

listener {
    timeout = 360
    on-timeout = systemd-ac-power || hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# ac settings
listener {
    timeout = 1800   
    on-timeout = systemd-ac-power && hyprlock
}

listener {
    timeout = 1860
    on-timeout = systemd-ac-power && hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
