command_timeout = 1000

[[battery.display]]
threshold = 20
style = 'yellow'

[[battery.display]]
threshold = 10
style = 'red'

[time]
disabled = true

[character]
success_symbol = "[>](green)"
error_symbol = "[x](red)"
vicmd_symbol = "[<](green)"

[git_status]
ahead = ">"
behind = "<"
deleted = "x"
diverged = "<>"

[directory]
read_only = " (read only)"

[aws]
disabled = true
symbol = "aws "

[azure]
disabled = true
symbol = "az "

[bun]
disabled = true
symbol = "bun "

[buf]
disabled = true
format = "via [$symbol]($style)"

[c]
disabled = true
symbol = "C "

[cmake]
disabled = true
symbol = "cmake "

[cobol]
disabled = true
symbol = "cobol "

[conda]
disabled = true
symbol = "conda "

[crystal]
disabled = true
symbol = "cr "

[daml]
disabled = true
symbol = "daml "

[dart]
disabled = true
symbol = "dart "

[deno]
disabled = true
symbol = "deno "

[dotnet]
disabled = true
symbol = ".NET "

[elixir]
disabled = true
symbol = "exs "

[elm]
disabled = true
symbol = "elm "

[fennel]
disabled = true
symbol = "fnl "

[fossil_branch]
disabled = true
symbol = "fossil "

[gcloud]
disabled = true
symbol = "gcp "

[git_branch]
symbol = "git "

[gleam]
disabled = true
symbol = "gleam "

[golang]
disabled = true
symbol = "go "

[gradle]
disabled = true
symbol = "gradel "

[guix_shell]
disabled = true
symbol = "guix "

[hg_branch]
disabled = true
symbol = "hg "

[java]
disabled = true
symbol = "java "

[julia]
disabled = true
symbol = "julia "

[kotlin]
disabled = true
symbol = "kt "

[lua]
disabled = true
symbol = "lua "

[memory_usage]
symbol = "memory "

[meson]
disabled = true
symbol = "meson "

[nats]
disabled = true
symbol = "nats "

[nim]
disabled = true
symbol = "nim "

[nix_shell]
disabled = true
symbol = "nix "

[nodejs]
disabled = true
symbol = "nodejs "

[ocaml]
disabled = true
symbol = "ml "

[opa]
disabled = true
symbol = "opa "

[os.symbols]
AIX = "aix "
Alpaquita = "alq "
AlmaLinux = "alma "
Alpine = "alp "
Amazon = "amz "
Android = "andr "
Arch = "rch "
Artix = "atx "
CentOS = "cent "
Debian = "deb "
DragonFly = "dfbsd "
Emscripten = "emsc "
EndeavourOS = "ndev "
Fedora = "fed "
FreeBSD = "fbsd "
Garuda = "garu "
Gentoo = "gent "
HardenedBSD = "hbsd "
Illumos = "lum "
Kali = "kali "
Linux = "lnx "
Mabox = "mbox "
Macos = "mac "
Manjaro = "mjo "
Mariner = "mrn "
MidnightBSD = "mid "
Mint = "mint "
NetBSD = "nbsd "
NixOS = "nix "
OpenBSD = "obsd "
OpenCloudOS = "ocos "
openEuler = "oeul "
openSUSE = "osuse "
OracleLinux = "orac "
Pop = "pop "
Raspbian = "rasp "
Redhat = "rhl "
RedHatEnterprise = "rhel "
RockyLinux = "rky "
Redox = "redox "
Solus = "sol "
SUSE = "suse "
Ubuntu = "ubnt "
Ultramarine = "ultm "
Unknown = "unk "
Void = "void "
Windows = "win "

[package]
disabled = true
symbol = "pkg "

[perl]
disabled = true
symbol = "pl "

[php]
disabled = true
symbol = "php "

[pijul_channel]
disabled = true
symbol = "pijul "

[pulumi]
disabled = true
symbol = "pulumi "

[purescript]
disabled = true
symbol = "purs "

[python]
disabled = false
symbol = "py "

[quarto]
disabled = true
symbol = "quarto "

[raku]
disabled = true
symbol = "raku "

[ruby]
disabled = true
symbol = "rb "

[rust]
disabled = true
symbol = "rs "

[solidity]
disabled = true
symbol = "solidarity "

[sudo]
symbol = "sudo "

[typst]
disabled = true
symbol = "typst "

[swift]
disabled = true
symbol = "swift " 

[terraform]
disabled = true
symbol = "terraform "

[zig]
disabled = true
symbol = "zig "
