#!/usr/bin/env bash

homedir="/home/uuu"

# TODO use pywal or a script to generate the different colour cache file formats
#      eg raw list, standard css, define css, json
#      be sure to define bg, fg, 8 standard and 8 bright colours - consider dim versions as well, and greys (eg micro uses standard, dim and bright bg colours)
#      for now, just rawdog them straight into the script, and in the near future read them from some kind of file. probably json with jq

#onedarkpro c/o https://github.com/sc0ttman/omarchy-one-dark-pro-theme/blob/main/alacritty.toml
foreground="#abb2bf"
background="#1e2229"
black="#282c34"
red="#e06c75"
green="#98c379"
yellow="#e5c07b"
blue="#61afef"
magenta="#c678dd"
cyan="#56b6c2"
white="#abb2bf"
brightblack="#5c6370"
brightred="#e06c75"   # Some variants use #be5046
brightgreen="#98c379"
brightyellow="#e5c07b"
brightblue="#61afef"
brightmagenta="#c678dd"
brightcyan="#56b6c2"
brightwhite="#c8ccd4"
dimblack="#21252b"
dimred="#be5046"
dimgreen="#7da869"
dimyellow="#d19a66"
dimblue="#528bff"
dimmagenta="#a678dd"
dimcyan="#4aa5b7"
dimwhite="#9aa2ad"

# everforest
background="#2d353b"
foreground="#d3c6aa"
black="#475258"
red="#e67e80"
green="#a7c080"
yellow="#dbbc7f"
blue="#7fbbb3"
magenta="#d699b6"
cyan="#83c092"
white="#d3c6aa"
brightblack="#475258"
brightred="#e67e80"
brightgreen="#a7c080"
brightyellow="#dbbc7f"
brightblue="#7fbbb3"
brightmagenta="#d699b6"
brightcyan="#83c092"
brightwhite="#d3c6aa"
dimblack="#232A2E"
dimred="#543A48"
dimgreen="#425047"
dimyellow="#4D4C43"
dimblue="#3A515D"

#nord
background="#2e3440"
foreground="#d8dee9"
black="#3b4252"
red="#bf616a"
green="#a3be8c"
yellow="#ebcb8b"
blue="#81a1c1"
magenta="#b48ead"
cyan="#88c0d0"
white="#e5e9f0"
brightblack="#4c566a"
brightred="#bf616a"
brightgreen="#a3be8c"
brightyellow="#ebcb8b"
brightblue="#81a1c1"
brightmagenta="#b48ead"
brightcyan="#8fbcbb"
brightwhite="#eceff4"
dimblack="#373e4d"
dimred="#94545d"
dimgreen="#809575"
dimyellow="#b29e75"
dimblue="#68809a"
dimmagenta="#8c738c"
dimcyan="#6d96a5"
dimwhite="#aeb3bb"
 
# TODO force reloads of apps that need them, and rewrite apps where otherwise possible

# alacritty - generate a toml
alacrittyconfig="[colors.primary]
foreground = \"$foreground\"
background = \"$background\"

[colors.normal]
black = \"$black\"
red = \"$red\"
green = \"$green\"
yellow = \"$yellow\"
blue = \"$blue\"
magenta = \"$magenta\"
cyan = \"$cyan\"
white = \"$white\"

[colors.bright]
black = \"$brightblack\"
red = \"$brightred\"
green = \"$brightgreen\"
yellow = \"$brightyellow\"
blue = \"$brightblue\"
magenta = \"$brightmagenta\"
cyan = \"$brightcyan\"
white = \"$brightwhite\"

[colors.dim]
black = \"$dimblack\"
red = \"$dimred\"
green = \"$dimgreen\"
yellow = \"$yellow\"
blue = \"$dimblue\"
magenta = \"$dimmagenta\"
cyan = \"$dimcyan\"
white = \"$dimwhite"\"

rm ${homedir}/.config/alacritty/themes/uuu.toml
touch ${homedir}/.config/alacritty/themes/uuu.toml
printf "${alacrittyconfig}" >> ${homedir}/.config/alacritty/themes/uuu.toml
# i dont love the below as a solution but it works to force a refresh on the alacritty config
printf " " >> ${homedir}/.config/alacritty/alacritty.toml
truncate -s-1 ${homedir}/.config/alacritty/alacritty.toml

# waybar (this feels dodgy but it works)
waybarconfig="@define-color bg ${background};
@define-color fg ${foreground};
@define-color im ${red};"

printf "${waybarconfig}" | tee ${homedir}/.config/colours/uuuwaybar.css > /dev/null

# dunst -lf  "${color0:-#ffffff}" \
#       -lb  "${color1:-#eeeeee}" \
#       -lfr "${color2:-#dddddd}" \
#       -nf  "${color3:-#cccccc}" \
#       -nb  "${color4:-#bbbbbb}" \
#       -nfr "${color5:-#aaaaaa}" \
#       -cf  "${color6:-#999999}" \
#       -cb  "${color7:-#888888}" \
#       -cfr "${color8:-#777777}" > /dev/null 2>&1 &

# tofi
toficonfig="background-color=${background}
text-color=${foreground}
border-color=${brightblack}
selection-color=${background}
selection-background=${foreground}"

rm ${homedir}/.config/tofi/themes/uuu
touch ${homedir}/.config/tofi/themes/uuu
printf "${toficonfig}" >> ${homedir}/.config/tofi/themes/uuu

# micro - make a .micro file. extra colours will come in handy here
# ## this will need some tweaking
# microconfig='
# color-link default "${foreground},${background}"  #fg, bg
# color-link comment "${blue},${background}"        #gray 1, bg
# color-link symbol "${foreground},${background}    #fg, bg
# color-link constant "#D699B6,#2d353b"             #brightmagenta, bg
# color-link constant.string "#DBBC7F,#2d353b"      #yellow, bg
# color-link constant.string.char "#DBBC7F,#2d353b" #yellow, bg
# color-link identifier "#A7C080,#2d353b"           #green, bg
# color-link statement "#E67E80,#2d353b"            #red, bg # maybe should be light red
# color-link preproc "#bf616a,#2d353b"              #red, bg
# color-link type "#dc7a7e,#2d353b"                 #red, bg
# color-link special "#E67E80,#2d353b"              #red, bg
# color-link underlined "#bf616a"                   #red
# color-link error "#E67E80,#2d353b"                #red, bg
# color-link hlsearch "#2d353b,#fe8019"             #bg,
# color-link diff-added "#a3be8c"                   #green
# color-link diff-modified "#ebcb8b"                #yellow
# color-link diff-deleted "#E67E80"                 #red
# color-link gutter-error "#E67E80,#2d353b"         #red, bg
# color-link gutter-warning "#dc7a7e,#2d353b"       #red, bg
# color-link line-number "#859289,#2d353b"          #gray 1, bg
# color-link current-line-number "#d3c6aa,#3D484D"  #fg, bg2 (bg2 is two steps lighter than bg)
# color-link cursor-line "#3D484D"                  #bg2
# color-link color-column "#4c566a"                 #bg3
# color-link statusline "#859289,#232A2E"           #gray 1, bg dim
# color-link tabbar "#d8dee9,#4c566a"               #gray 1, bg3 (its actually way lighter than gray 1 but we dont need more fucking colours)
# color-link todo "#E57E00,#2d353b"                 #orange, bg'

printf "${microconfig}"

# dunst
dunstconfig="
[global]
    frame_color = \"${brightblack}\"

[urgency_low]
    background = \"${background}\"
    foreground = \"${foreground}\"
    highlight = \"${green}\"

[urgency_normal]
    background = \"${background}\"
    foreground = \"${foreground}\"
    highlight = \"${green}\"

[urgency_critical]
	background = \"${dimred}\"
    foreground = \"${foreground}\"
    highlight = \"${brightred}\""

printf "${dunstconfig}" > ${homedir}/.config/dunst/dunstcolors
${homedir}/.config/dunst/dunstcombiner
killall dunst
notify-send -u low "dunst test" "low urgency"
notify-send -u normal "dunst test" "normal urgency"
notify-send -t 10000 -u critical "dunst test" "critical urgency"

# gtk c/o oomox

