#!/usr/bin/env bash

homedir="/home/uuu"

hextohsl() {
  echo $(magick xc:"$1" -colorspace HSL -format "%[pixel:u]" info: | sed 's/hsl(//;s/%)//g;s/)//' | awk -F',' '{printf "%.0f,%.0f,%.0f\n", $1, $2, $3}')
}

# depth 8 gives you single precision hex
hsltohex() {
  echo $(magick canvas:"hsl($1,$2%,$3%)" -depth 8 -format "%[hex:u]" info:)
}

#todo check that the schemes folder is here and if not clone it in
#todo allow for pywal or tinty to generate colours

base16schemes=$(ls -w 1 "${homedir}/scripts/schemes/base16" | sed 's/\.yaml//g')
base24schemes=$(ls -w 1 "${homedir}/scripts/schemes/base24" | sed 's/\.yaml//g')

selectedscheme=$(printf '%s/n' "$base16schemes" | tofi) || exit 0

echo $selectedscheme

base00=$(cat "${homedir}/scripts/schemes/base16/${selectedscheme}.yaml" | yq .palette.base00)
base01=$(cat "${homedir}/scripts/schemes/base16/${selectedscheme}.yaml" | yq .palette.base01)
base02=$(cat "${homedir}/scripts/schemes/base16/${selectedscheme}.yaml" | yq .palette.base02)
base03=$(cat "${homedir}/scripts/schemes/base16/${selectedscheme}.yaml" | yq .palette.base03)
base04=$(cat "${homedir}/scripts/schemes/base16/${selectedscheme}.yaml" | yq .palette.base04)
base05=$(cat "${homedir}/scripts/schemes/base16/${selectedscheme}.yaml" | yq .palette.base05)
base06=$(cat "${homedir}/scripts/schemes/base16/${selectedscheme}.yaml" | yq .palette.base06)
base07=$(cat "${homedir}/scripts/schemes/base16/${selectedscheme}.yaml" | yq .palette.base07)
base08=$(cat "${homedir}/scripts/schemes/base16/${selectedscheme}.yaml" | yq .palette.base08)
base09=$(cat "${homedir}/scripts/schemes/base16/${selectedscheme}.yaml" | yq .palette.base09)
base0A=$(cat "${homedir}/scripts/schemes/base16/${selectedscheme}.yaml" | yq .palette.base0A)
base0B=$(cat "${homedir}/scripts/schemes/base16/${selectedscheme}.yaml" | yq .palette.base0B)
base0C=$(cat "${homedir}/scripts/schemes/base16/${selectedscheme}.yaml" | yq .palette.base0C)
base0D=$(cat "${homedir}/scripts/schemes/base16/${selectedscheme}.yaml" | yq .palette.base0D)
base0E=$(cat "${homedir}/scripts/schemes/base16/${selectedscheme}.yaml" | yq .palette.base0E)
base0F=$(cat "${homedir}/scripts/schemes/base16/${selectedscheme}.yaml" | yq .palette.base0F)

echo base00 $base00

# TODO use pywal or a script to generate the different colour cache file formats
#      eg raw list, standard css, define css, json
#      be sure to define bg, fg, 8 standard and 8 bright colours - consider dim versions as well, and greys (eg micro uses standard, dim and bright bg colours)
#      for now, just rawdog them straight into the script, and in the near future read them from some kind of file. probably json with jq

# #onedarkpro c/o https://github.com/sc0ttman/omarchy-one-dark-pro-theme/blob/main/alacritty.toml
# foreground="#abb2bf"
# background="#1e2229"
# black="#282C34"
# red="#e06c75"
# green="#98c379"
# yellow="#e5c07b"
# blue="#61afef"
# magenta="#c678dd"
# cyan="#56b6c2"
# white="#abb2bf"
# brightblack="#5c6370"
# brightred="#e06c75"   # Some variants use #be5046
# brightgreen="#98c379"
# brightyellow="#e5c07b"
# brightblue="#61afef"
# brightmagenta="#c678dd"
# brightcyan="#56b6c2"
# brightwhite="#c8ccd4"
# dimblack="#21252b"
# dimred="#be5046"
# dimgreen="#7da869"
# dimyellow="#d19a66"
# dimblue="#528bff"
# dimmagenta="#a678dd"
# dimcyan="#4aa5b7"
# dimwhite="#9aa2ad"

# # everforest
# background="#2d353b"
# foreground="#d3c6aa"
# black="#475258"
# red="#e67e80"
# green="#a7c080"
# yellow="#dbbc7f"
# blue="#7fbbb3"
# magenta="#d699b6"
# cyan="#83c092"
# white="#d3c6aa"
# brightblack="#475258"
# brightred="#e67e80"
# brightgreen="#a7c080"
# brightyellow="#dbbc7f"
# brightblue="#7fbbb3"
# brightmagenta="#d699b6"
# brightcyan="#83c092"
# brightwhite="#d3c6aa"
# dimblack="#232A2E"
# dimred="#543A48"
# dimgreen="#425047"
# dimyellow="#4D4C43"
# dimblue="#3A515D"

# TODO color processing to generate a dark black, a light black, a dark red and green, and a grey
IFS=',' read -r -a blackhsl <<< "$(hextohsl "$black")"

blacksatstep=1
blacklumstep=3

backgrounddim="#$(magick xc:"${base00}" -fill black -colorize 22% -depth 8 -format "%[hex:u]" info:)"
background0="#$(hsltohex "${blackhsl[0]}" $((${blackhsl[1]}+($blacksatstep*4))) $((${blackhsl[2]}-($blacklumstep*4))))"
background1="#$(hsltohex "${blackhsl[0]}" $((${blackhsl[1]}+($blacksatstep*3))) $((${blackhsl[2]}-($blacklumstep*3))))"
background2="#$(hsltohex "${blackhsl[0]}" $((${blackhsl[1]}+($blacksatstep*2))) $((${blackhsl[2]}-($blacklumstep*2))))"
background3="#$(hsltohex "${blackhsl[0]}" $((${blackhsl[1]}+$blacksatstep)) $((${blackhsl[2]}-$blacklumstep)))"
background4="#$black"
background5="#$(hsltohex "${blackhsl[0]}" $((${blackhsl[1]}-blacksatstep)) $((${blackhsl[2]}+blacklumstep)))"

# these are not quite there but theyre pretty damn close
backgroundred="#$(magick xc:"${base08}" -fill "${backgrounddim}" -colorize 75% -depth 8 -format "%[hex:u]" info:)"
backgroundgreen="#$(magick xc:"${base0B}" -fill "${backgrounddim}" -colorize 75% -depth 8 -format "%[hex:u]" info:)"
backgroundyellow="#$(magick xc:"${base0A}" -fill "${backgrounddim}" -colorize 75% -depth 8 -format "%[hex:u]" info:)"
backgroundblue="#$(magick xc:"${base0D}" -fill "${backgrounddim}" -colorize 75% -depth 8 -format "%[hex:u]" info:)"

darkestbackground= #TODO base11 or generated
dimbackground="$backgrounddim" #TODO base10 or generated
background="$base00" #base00
grey="$base03" #base03
lightgrey="$base04" #base04
foreground="$base05" #base05
black="$base02" #base02
red="$base08" #base08
orange="$base09" #base09
yellow="$base0A" #base0A
green="$base0B" #base0B
cyan="$base0C" #base0C
blue="$base0D" #base0D
magenta="$base0E" #base0E
white="$base06" #base06
brightblack="$base02" #TODO
brightred="$base08" #TODO base12
brightyellow="$base0A" #TODO base13
brightgreen="$base0B" #TODO base14
brightcyan="$base0C" #TODO base15
brightblue="$base0D" #TODO base16
brightmagenta="$base0E" #TODO base17
brightwhite="$base06" #TODO
dimblack="$base02" #TODO
dimred="$backgroundred" #generated
dimyellow="$backgroundyellow" #generated
dimgreen="$backgroundgreen" #generated
dimcyan="$backgroundblue" #TODO
dimblue="$backgroundblue" #generated
dimmagenta="$backgroundblue" #TODO
dimwhite="$base06" #TODO

# TODO force reloads of apps that need them, and rewrite apps where otherwise possible

# alacritty - generate a toml
alacrittyconfig="[colors.primary]
foreground = \"$foreground\"
background = \"$background\"

[colors.normal]
black = \"$black\"
red = \"$red\"
green = \"$green\"
yellow = \"$yellow\"
blue = \"$blue\"
magenta = \"$magenta\"
cyan = \"$cyan\"
white = \"$white\"

[colors.bright]
black = \"$brightblack\"
red = \"$brightred\"
green = \"$brightgreen\"
yellow = \"$brightyellow\"
blue = \"$brightblue\"
magenta = \"$brightmagenta\"
cyan = \"$brightcyan\"
white = \"$brightwhite\"

[colors.dim]
black = \"$dimblack\"
red = \"$dimred\"
green = \"$dimgreen\"
yellow = \"$yellow\"
blue = \"$dimblue\"
magenta = \"$dimmagenta\"
cyan = \"$dimcyan\"
white = \"$dimwhite"\"

rm ${homedir}/.config/alacritty/themes/uuu.toml
touch ${homedir}/.config/alacritty/themes/uuu.toml
printf "${alacrittyconfig}" >> ${homedir}/.config/alacritty/themes/uuu.toml
# i dont love the below as a solution but it works to force a refresh on the alacritty config
printf " " >> ${homedir}/.config/alacritty/alacritty.toml
truncate -s-1 ${homedir}/.config/alacritty/alacritty.toml

# waybar (this feels dodgy but it works)
waybarconfig="@define-color bg ${background};
@define-color fg ${foreground};
@define-color im ${red};"

printf "${waybarconfig}" | tee ${homedir}/.config/colours/uuuwaybar.css > /dev/null

# tofi
toficonfig="background-color=${background}
text-color=${foreground}
border-color=${foreground}
selection-color=${background}
selection-background=${foreground}"

rm ${homedir}/.config/tofi/themes/uuu
touch ${homedir}/.config/tofi/themes/uuu
printf "${toficonfig}" >> ${homedir}/.config/tofi/themes/uuu

# dunst
# note the dimred misbehaves with some themes
echo backgroundred "${backgroundred}"
dunstconfig="
[global]
    frame_color = \"${foreground}\"

[urgency_low]
    background = \"${background}\"
    foreground = \"${foreground}\"
    highlight = \"${green}\"

[urgency_normal]
    background = \"${background}\"
    foreground = \"${foreground}\"
    highlight = \"${green}\"

[urgency_critical]
    background = \"${backgroundred}\"
    foreground = \"${foreground}\"
    highlight = \"${brightred}\""

printf "${dunstconfig}" > ${homedir}/.config/dunst/dunstcolors
${homedir}/.config/dunst/dunstcombiner
killall dunst
notify-send -u low "dunst test" "low urgency"
notify-send -u normal "dunst test" "normal urgency"
notify-send -t 10000 -u critical "dunst test" "critical urgency"

# sddm
sddmconfig="background=\"${background}\"
foreground=\"${foreground}\"
dim=\"${black}\""

cat ${homedir}/.config/sddm/themerules.conf > /usr/share/sddm/themes/uuusddm/theme.conf
printf "${sddmconfig}" >> /usr/share/sddm/themes/uuusddm/theme.conf

#TODO gtk
# *16 for the character height, +10 for the padding and border on tofi
height=$(($((12*16))+10))

# prompt user for a theme color
themecoloroptions="gray
foreground
white
red
orange
yellow
green
cyan
blue
magenta
special"

themecolor=$(printf "%s\n" "$themecoloroptions" | tofi --prompt-text "sel: " --height "$height" --num-results "13")

theme=$(gsettings get org.gnome.desktop.interface gtk-theme)
gsettings set org.gnome.desktop.interface gtk-theme ''
sleep 1
gsettings set org.gnome.desktop.interface gtk-theme $theme

#TODO hyprlock

#TODO hyprland borders

#TODO grim screenshotscript
