[colors.primary]
foreground = "#abb2bf"
background = "#282c34"

[colors.normal]
black = "#3e4451"
red = "#e06c75"
green = "#98c379"
yellow = "#e5c07b"
blue = "#61afef"
magenta = "#c678dd"
cyan = "#56b6c2"
white = "#b6bdca"

[colors.bright]
black = "#3e4451"
red = "#e06c75"
green = "#98c379"
yellow = "#e5c07b"
blue = "#61afef"
magenta = "#c678dd"
cyan = "#56b6c2"
white = "#b6bdca"

[colors.dim]
black = "#3e4451"
red = "#4F353C"
green = "#3D4A3D"
yellow = "#e5c07b"
blue = "#30455B"
magenta = "#30455B"
cyan = "#30455B"
white = "#b6bdca"