[window]
title = "alacritty"
dimensions = { columns = 80, lines = 24 }
padding = { x = 1, y = 1 }

[font]
normal = { family = "terminus", style = "Regular" }
bold  = { family = "terminus", style = "Bold" }
italic = { family = "terminus", style = "Italic" }
bold_italic = { family = "terminus", style = "Bold Italic" }
size = 14

[general]
import = [
  "~/.config/alacritty/themes/uuu.toml"
  #"~/.config/alacritty/themes/djakovic.toml"
]

[keyboard]
bindings = [
{ key = "PageUp", action = "ScrollLineUp" },
{ key = "PageUp", mods="Control", action = "ScrollHalfPageUp" },
{ key = "PageDown", action = "ScrollLineDown" },
{ key = "PageDown", mods="Control", action = "ScrollHalfPageDown" },
]
