[font]
normal = { family = "Iosevka Custom", style = "Regular" }
bold  = { family = "Iosevka Custom", style = "Bold" }
italic = { family = "Iosevka Custom", style = "Italic" }
bold_italic = { family = "Iosevka Custom", style = "Bold Italic" }
size = 11

offset = { x = 0, y = -2 }
