[defaults]
format = "{time}\n"

[[sessions]]
id = "work"
name = "Work"
duration = "25s"
command = "notify-send 'Work Done!'"

[[sessions]]
autostart = "true"
id = "rest"
name = "Rest"
duration = "5s"
command = "notify-send 'Rest Done!'"
